### ISSUE TITLE
Page Builder by SiteOrigin compatiblity

### ISSUE THREAD

**Issue by lukasjuhas** [lukasjuhas/lj-maintenance-mode#20]
From support:
"There is a conflict between Maintence Mode and Page Builder by SiteOrigin plug-in. 

When Page Builder by SiteOrigin is active it prevents the maintence mode message from being displayed, ie only the white rectangle is displayed, without a message."

Anyone else having issues?

**Comment by lukasjuhas** [comment]
Update: Contacted SiteOrigin regarding possible compatibility integration.

**Comment by lukasjuhas** [comment]
I cannot replicate this.

**Comment by kmaxima** [comment]
I can confirm this is an issue.  Have Page Builder by SiteOrigin installed and when activated maintenance mode shows unstyled front page content instead of the maintenance page content.  As soon as I deactivate the Page Builder plugin then maintenance mode works properly. It appears that this only happens if your homepage is a page built using the Page Builder editor. If your homepage is a static page with only html or a post listing page then there is not a conflict. Perhaps this is why you were unable to reproduce this issue.   I know you closed this out but please let me know if you would like any assistance in tracking it down.

**Comment by lukasjuhas** [comment]
Thanks for your feedback and info @kmaxima, I hope to find a moment and test this soon.

I let you know the results, might implement possible fix.

**Comment by lukasjuhas** [comment]
Fixed in #39, will be included in the next release.
